### ISSUE TITLE
Can't clear cache - permission

### ISSUE THREAD

**Issue by OneX** [thoughtfulweb/craft-litespeedcache#2]
<img width="725" alt="screenshot 2019-02-13 17 50 51" src="https://user-images.githubusercontent.com/3229119/52878505-15dc7600-315d-11e9-8d4c-9246e98529a7.png">

**Comment by jsmrtn** [comment]
Hi @OneX,

I'd suggest you ensure that the user that runs PHP has permissions to modify the folder at `/home/fourinc/lscache`, this would be a question for your hosting provider.

Thanks.

**Comment by OneX** [comment]
This is answer from host and question for you:

Hi Josip,

Yes, of course. LiteSpeed Cache was designed by LiteSpeed to work with LiteSpeed PHP. LS Cache works without any issues with the WordPress and Drupal plugins and, so far, we only see this problem with your Craft sites.

The question for the Craft plugin developer is, does their plugin check and/or try to modify the permissions or ownership of the cache folder at any time?

The reason I ask is, PHP runs as user. For example, PHP is owned by username when the username user launches PHP. But the plugin seems to be changing the cache folder to "nobody" ownership at install time. If plugin changes the ownership of any file or folder it will render the file or folder unusable by PHP.

**Comment by jsmrtn** [comment]
The plugin doesn't modify or change ownership of anything. It's throwing an error when it's trying to run [this function](https://github.com/thoughtfulweb/craft-litespeedcache/blob/9ed680f07de67c56c7f35731ffb3a50492911586/src/services/ClearCache.php#L31) which essentially is just an `rm -rf` of the folder you've defined in the settings. It doesn't change the folder permissions, it doesn't technically interact with the folder at all other than to run the removal function it when you run a global purge.

This is why I believe the issue is with the user that PHP runs as, it doesn't have permissions to delete anything from the `lscache` folder in the user directory.

I've not seen this issue anywhere else with any of the other installations that are running this plugin. I imagine they are not seeing this issue with Wordpress or Drupal as they do not interact with the cache folder in this way.
